//---- début du fichier batiment1.inc ----//

    //-------------------------------------------
    //  author : Winael
    //  date : 2015-03-10
    //-------------------------------------------

    #ifndef (Inclus_Batiment1)

        #declare Inclus_Batiment1 = 1;

        #declare origine = <0, 0, 0> ;

        //  INCLUDE  //

            #include "batiments/batiment1/rdc/rdc.inc"

    #end

//---- fin du fichier batiment1.inc ----//